// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJjXLI6QB4j2-v5YcKgESfFJjRcvsVfFw',
    appId: '1:1019852036603:web:7e162849f7af012615d35e',
    messagingSenderId: '1019852036603',
    projectId: 'charter-bd51b',
    authDomain: 'charter-bd51b.firebaseapp.com',
    storageBucket: 'charter-bd51b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3l2nHGSNt2K6Si50zUtTz3MqfoCSWvsE',
    appId: '1:1019852036603:android:e35e3aa3e5b9a53d15d35e',
    messagingSenderId: '1019852036603',
    projectId: 'charter-bd51b',
    storageBucket: 'charter-bd51b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_fVe-gyHt7c-YrreWleAJhTR1mAYKthI',
    appId: '1:1019852036603:ios:76f5d79ac47254ab15d35e',
    messagingSenderId: '1019852036603',
    projectId: 'charter-bd51b',
    storageBucket: 'charter-bd51b.appspot.com',
    iosClientId:
        '1019852036603-7a6jj8vafq0f9d844du6ms97btrq1t1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.charterAppliTravauxMro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_fVe-gyHt7c-YrreWleAJhTR1mAYKthI',
    appId: '1:1019852036603:ios:76f5d79ac47254ab15d35e',
    messagingSenderId: '1019852036603',
    projectId: 'charter-bd51b',
    storageBucket: 'charter-bd51b.appspot.com',
    iosClientId:
        '1019852036603-7a6jj8vafq0f9d844du6ms97btrq1t1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.charterAppliTravauxMro',
  );
}
